# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  image: sebp/elk  
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"

dummy-app:
  build: ./DummyApp
  ports:
    - "8080:80"
  links: 
    - elk
  volumes:
    - ./logs/sysdig:/var/log/sysdig/

sysdig:
  image: sysdig/sysdig
  volumes:
    - ./logs/sysdig/:/var/log/sysdig/
