version: "2.3"

services:
    victim:
        build: "./victim"
        ports:
            - "80:80"

    client:
        build: "./client"
        scale: 3
        links:
          - victim

    attacker:
        build: "./attacker"
        scale: 0
        links:
          - victim

